-- Licensed to the Apache Software Foundation (ASF) under one or more
-- contributor license agreements.  See the NOTICE file distributed with
-- this work for additional information regarding copyright ownership.
-- The ASF licenses this file to You under the Apache License, Version 2.0
-- (the "License"); you may not use this file except in compliance with
-- the License.  You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- The workflow instance repository, when it is a database rather than a
-- Lucene index.
--
-- The Lucene repository is a search index used as a store: instances
-- cannot be cleared except by deleting the directory, and instances left
-- by one engine are read by the next. Switching engines with a populated
-- index meant the new engine picked up the old engine's finished
-- instances and worked through them before touching anything new.
--
-- Applied by bin/oodt on every start, before the Workflow Manager is
-- launched, and only when the tables are absent. It is done at start rather
-- than only at setup because the way this actually went wrong was clearing
-- data/ between runs and restarting: setup is not re-run then, HSQLDB
-- recreates an empty database, and the Workflow Manager comes up perfectly
-- healthy, loads its policy, registers its events and then fails every single
-- workflow start against the missing table.
--
-- Written to match what the DataSourceWorkflowInstanceRepository issues,
-- which is unquoted SQL against these two tables.

CREATE TABLE workflow_instances (
  workflow_instance_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1)
    NOT NULL PRIMARY KEY,
  workflow_instance_status VARCHAR(255),
  workflow_id VARCHAR(255) NOT NULL,
  current_task_id VARCHAR(255) NOT NULL,
  start_date_time VARCHAR(255),
  end_date_time VARCHAR(255),
  current_task_start_date_time VARCHAR(255),
  current_task_end_date_time VARCHAR(255),
  priority DOUBLE,
  times_blocked INTEGER DEFAULT 0,
  waiting_on VARCHAR(255) DEFAULT NULL
);

CREATE TABLE workflow_instance_metadata (
  workflow_instance_id INTEGER NOT NULL,
  workflow_met_key VARCHAR(1000) NOT NULL,
  workflow_met_val VARCHAR(1000) NOT NULL
);

CREATE INDEX workflow_instance_metadata_id_idx
  ON workflow_instance_metadata (workflow_instance_id);
